###
# This docker-compose file contains optional MongoDB-reader service
# for Mainflux platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these optional service, execute command:
# docker-compose -f docker/docker-compose.yml -f docker/addons/mongodb-reader/docker-compose.yml up
# from project root. MongoDB service is defined in docker/addons/mongodb-writer/docker-compose.yml.
###

version: "3"

networks:
  docker_mainflux-base-net:
    external: true

services:
  mongodb-reader:
    image: mainflux/mongodb-reader:latest
    container_name: mainflux-mongodb-reader
    restart: on-failure
    environment:
      MF_MONGO_READER_LOG_LEVEL: debug
      MF_THINGS_URL: things:8183
      MF_MONGO_READER_PORT: 8904
      MF_MONGO_READER_DB_NAME: mainflux
      MF_MONGO_READER_DB_HOST: mongodb
      MF_MONGO_READER_DB_PORT: 27017
    ports:
      - 8904:8904
    networks:
      - docker_mainflux-base-net
