apiVersion: v1
kind: Service
metadata:
  name: mainflux-nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 8883
    name: mqtt
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mainflux-nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: mainflux-secret
      - name: configmap-volume
        configMap:
          name: mainflux-nginx-config
      containers:
      - name: mainflux-nginx
        image: nginx:1.13-alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8883
        volumeMounts:
        - mountPath: /etc/ssl/certs/mainflux-server.crt
          name: secret-volume
          subPath: mainflux-server.crt
        - mountPath: /etc/ssl/private/mainflux-server.key
          name: secret-volume
          subPath: mainflux-server.key
        - mountPath: /etc/ssl/certs/dhparam.pem
          name: secret-volume
          subPath: dhparam.pem
        - mountPath: /etc/nginx/nginx.conf
          name: configmap-volume
          subPath: nginx.conf
