---
apiVersion: v1
kind: Service
metadata:
  name: normalizer
  labels:
    component: normalizer
spec:
  selector:
    component: normalizer
  ports:
  - port: 8184
    name: http
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: normalizer
  namespace: grpc-services
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: normalizer
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: normalizer
  labels:
    component: normalizer
spec:
  template:
    metadata:
      labels:
        component: normalizer
    spec:
      containers:
      - name: mainflux-normalizer
        image: mainflux/normalizer:latest
        imagePullPolicy: Always
        env:
        - name: MF_NATS_URL
          value: "nats://nats-cluster.nats-io:4222"
        - name: MF_NORMALIZER_PORT
          value: "8184"
        livenessProbe:
          httpGet:
            path: /version
            port: 8184
          initialDelaySeconds: 3
          periodSeconds: 3
