###
# This docker-compose file contains optional InfluxDB-reader service for the Mainflux
# platform. Since this service is optional, this file is dependent on the docker-compose.yml
# file from <project_root>/docker/. In order to run InfluxDB-reader service, core services,
# as well as the network from the core composition, should be already running.
###

version: "3"

networks:
  docker_mainflux-base-net:
    external: true

services:
  influxdb-reader:
    image: mainflux/influxdb-reader:latest
    container_name: mainflux-influxdb-reader
    restart: on-failure
    environment:
      MF_INFLUX_READER_LOG_LEVEL: debug
      MF_THINGS_URL: things:8183
      MF_INFLUX_READER_PORT: 8905
      MF_INFLUX_READER_DB_NAME: mainflux
      MF_INFLUX_READER_DB_HOST: mainflux-influxdb
      MF_INFLUX_READER_DB_PORT: 8086
      MF_INFLUX_READER_DB_USER: mainflux
      MF_INFLUX_READER_DB_PASS: mainflux
    ports:
      - 8905:8905
    networks:
      - docker_mainflux-base-net
