apiVersion: v1
kind: PersistentVolume
metadata:
  name: mainflux-influxdb-data-disk
  labels:
    name: mainflux-influxdb-data-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/influxdb-0
  persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mainflux-influxdb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mainflux-influxdb
  labels:
    name: mainflux-influxdb
spec:
  containers:
    - name: mainflux-influxdb
      image: influxdb:1.5.2-alpine
      env:
        - name: INFLUXDB_DB
          value: "mainflux"
        - name: INFLUXDB_ADMIN_USER
          value: "mainflux"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "mainflux"
      ports:
        - containerPort: 8086
      volumeMounts:
        - mountPath: /var/lib/influxdb
          name: mainflux-influxdb-data
  volumes:
    - name: mainflux-influxdb-data
      persistentVolumeClaim:
        claimName: mainflux-influxdb-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mainflux-influxdb
  labels:
    name: mainflux-influxdb
spec:
  ports:
    - port: 8086
  selector:
    name: mainflux-influxdb
